// Flat ESLint config migrated from legacy .eslintrc.json
// Original file was generated by projen; adapted for ESLint v9 flat config.

const js = require('@eslint/js');
const typescript = require('typescript-eslint');
const importPlugin = require('eslint-plugin-import');
const prettierPlugin = require('eslint-plugin-prettier');
const path = require('node:path');

const ignores = [
  'src/LambdaInterface.ts',
  '*.js',
  '*.d.ts',
  'node_modules/',
  '*.generated.ts',
  'coverage',
];

module.exports = [
  js.configs.recommended,
  ...typescript.configs.recommended,
  {
    ignores,
  },
  {
    plugins: {
      '@typescript-eslint': typescript.plugin,
      import: importPlugin,
      prettier: prettierPlugin,
    },
    languageOptions: {
      parser: typescript.parser,
      parserOptions: {
        ecmaVersion: 2018,
        sourceType: 'module',
        project: path.join(process.cwd(), 'tsconfig.dev.json'),
        tsconfigRootDir: process.cwd(),
      },
      globals: {
        afterAll: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        beforeEach: 'readonly',
        describe: 'readonly',
        expect: 'readonly',
        it: 'readonly',
        jest: 'readonly',
        test: 'readonly',
      },
    },
    files: ['src/**/*.ts', 'test/**/*.ts'],
    ignores,
    settings: {
      'import/parsers': {
        '@typescript-eslint/parser': ['.ts', '.tsx'],
      },
      'import/resolver': {
        node: {},
        typescript: {
          project: './tsconfig.dev.json',
          alwaysTryTypes: true,
        },
      },
    },
    rules: {
      curly: ['error', 'multi-line', 'consistent'],
      '@typescript-eslint/no-require-imports': 'error',
      'import/no-extraneous-dependencies': [
        'error',
        {
          devDependencies: ['**/test/**', '**/build-tools/**'],
          optionalDependencies: false,
          peerDependencies: true,
        },
      ],
      'import/no-unresolved': ['error'],
      'import/order': [
        'warn',
        {
          groups: ['builtin', 'external'],
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      'import/no-duplicates': ['error'],
      'no-shadow': ['off'],
      '@typescript-eslint/no-shadow': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      'no-return-await': ['off'],
      '@typescript-eslint/return-await': 'error',
      'dot-notation': ['error'],
      'no-bitwise': ['error'],
      '@typescript-eslint/member-ordering': [
        'error',
        {
          default: [
            'public-static-field',
            'public-static-method',
            'protected-static-field',
            'protected-static-method',
            'private-static-field',
            'private-static-method',
            'field',
            'constructor',
            'method',
          ],
        },
      ],
      // Allow namespaces for logical grouping (Permissions namespace)
      '@typescript-eslint/no-namespace': 'off',
      // Ignore unused vars/args when prefixed with underscore
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'prettier/prettier': 'error',
    },
  },
  {
    // Test file overrides
    files: ['test/**/*.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  {
    files: ['.projenrc.js'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
      'import/no-extraneous-dependencies': 'off',
    },
  },
];
