import { Grant, IGrantable } from 'aws-cdk-lib/aws-iam';
import { IKey } from 'aws-cdk-lib/aws-kms';
import {
  IStringParameter,
  ParameterReference,
  ParameterTier,
  StringParameter,
} from 'aws-cdk-lib/aws-ssm';
import { RemovalPolicy, ResourceEnvironment, Stack } from 'aws-cdk-lib/core';
import { Construct } from 'constructs';
import { ResourceType, SopsSync, SopsSyncOptions } from './SopsSync';

/**
 * The configuration options of the StringParameter
 */
export interface SopsCommonParameterProps extends SopsSyncOptions {
  /**
   * The tier of the string parameter
   *
   * @default - undefined
   */
  readonly tier?: ParameterTier;
  /**
   * Information about the parameter that you want to add to the system.
   *
   * @default none
   */
  readonly description?: string;
  /**
   * The customer-managed encryption key to use for encrypting the secret value.
   *
   * @default - A default KMS key for the account and region is used.
   */
  readonly encryptionKey: IKey;
}

export interface SopsStringParameterProps extends SopsCommonParameterProps {
  /**
   * The name of the parameter.
   *
   * @default - a name will be generated by CloudFormation
   */
  readonly parameterName?: string;
}

/**
 * A drop in replacement for the normal String Parameter, that is populated with the encrypted
 * content of the given sops file.
 */
export class SopsStringParameter extends Construct implements IStringParameter {
  private readonly parameter: StringParameter;
  readonly sync: SopsSync;
  readonly encryptionKey: IKey;
  readonly stack: Stack;
  readonly env: ResourceEnvironment;
  readonly parameterArn: string;
  readonly parameterName: string;
  readonly parameterType: string;
  readonly stringValue: string;
  readonly parameterRef: ParameterReference;

  public constructor(
    scope: Construct,
    id: string,
    props: SopsStringParameterProps,
  ) {
    super(scope, id);

    this.encryptionKey = props.encryptionKey;
    this.stack = Stack.of(scope);
    this.env = {
      account: this.stack.account,
      region: this.stack.region,
    };

    this.parameter = new StringParameter(this, 'Resource', {
      parameterName: props.parameterName,
      description: props.description,
      tier: props.tier,
      stringValue: ' ',
    });

    this.parameterArn = this.parameter.parameterArn;
    this.parameterName = this.parameter.parameterName;
    this.parameterType = this.parameter.parameterType;
    this.stringValue = this.parameter.stringValue;
    this.parameterRef = this.parameter.parameterRef;

    this.sync = new SopsSync(this, 'SopsSync', {
      encryptionKey: this.parameter.encryptionKey,
      target: this.parameter.parameterName,
      resourceType: ResourceType.PARAMETER,
      parameterNames: [props.parameterName ?? this.parameter.parameterName],
      ...(props as SopsSyncOptions),
    });
  }
  grantRead(grantee: IGrantable): Grant {
    if (this.encryptionKey) {
      this.encryptionKey.grantDecrypt(grantee);
    }
    return this.parameter.grantRead(grantee);
  }
  grantWrite(grantee: IGrantable): Grant {
    if (this.encryptionKey) {
      this.encryptionKey.grantEncrypt(grantee);
    }
    return this.parameter.grantWrite(grantee);
  }
  applyRemovalPolicy(policy: RemovalPolicy): void {
    this.parameter.applyRemovalPolicy(policy);
  }
}
