import {
  AddToResourcePolicyResult,
  Grant,
  IGrantable,
  PolicyStatement,
  Role,
  ServicePrincipal,
} from 'aws-cdk-lib/aws-iam';
import { IKey, ViaServicePrincipal } from 'aws-cdk-lib/aws-kms';
import { CfnScheduleGroup } from 'aws-cdk-lib/aws-scheduler';
import {
  ISecret,
  ISecretAttachmentTarget,
  ReplicaRegion,
  RotationSchedule,
  RotationScheduleOptions,
  Secret,
  SecretProps,
  SecretReference,
} from 'aws-cdk-lib/aws-secretsmanager';
import { ITopic, Topic } from 'aws-cdk-lib/aws-sns';
import {
  Names,
  RemovalPolicy,
  ResourceEnvironment,
  SecretsManagerSecretOptions,
  SecretValue,
  Stack,
} from 'aws-cdk-lib/core';
import { Construct } from 'constructs';
import {
  ResourceType,
  SopsSync,
  SopsSyncOptions,
  SopsExpirationConfig,
} from './SopsSync';

export enum RawOutput {
  /**
   * Parse the secret as a string
   */
  STRING = 'STRING',
  /**
   * Parse the secret as a binary
   */
  BINARY = 'BINARY',
}

/**
 * Options for expiration notifications on secret keys.
 * When set, the Lambda syncer will look for keys in the secret that end with
 * the configured suffix (e.g. `gitlab_token_expiration`) and create
 * EventBridge Scheduler one-time schedules that publish to SNS before each
 * expiration date.
 */
export interface ExpirationOptions {
  /**
   * An existing SNS topic to publish expiration notifications to.
   * If not provided, a new SNS topic will be created automatically.
   *
   * @default - A new SNS topic is created
   */
  readonly notificationTopic?: ITopic;

  /**
   * The suffix used to identify expiration date keys in the secret.
   * For example, a suffix of `_expiration` will match any key like
   * `gitlab_token_expiration` and treat its value as the expiration date
   * for `gitlab_token`.
   *
   * @default '_expiration'
   */
  readonly expirationSuffix?: string;

  /**
   * Number of days before the expiration date to send the SNS notification.
   *
   * @default 14
   */
  readonly daysBeforeExpiration?: number;
}

/**
 * The configuration options of the SopsSecret
 */
export interface SopsSecretProps extends SopsSyncOptions {
  /**
   * Should the secret parsed and transformed to json?
   * @default - undefined - STRING for binary secrets, else no raw output
   */
  readonly rawOutput?: RawOutput;
  /**
   * An optional, human-friendly description of the secret.
   *
   * @default - No description.
   */
  readonly description?: string;
  /**
   * The customer-managed encryption key to use for encrypting the secret value.
   *
   * @default - A default KMS key for the account and region is used.
   */
  readonly encryptionKey?: IKey;
  /**
   * A name for the secret. Note that deleting secrets from SecretsManager does not happen immediately, but after a 7 to
   * 30 days blackout period. During that period, it is not possible to create another secret that shares the same name.
   *
   * @default - A name is generated by CloudFormation.
   */
  readonly secretName?: string;
  /**
   * Policy to apply when the secret is removed from this stack.
   *
   * @default - Not set.
   */
  readonly removalPolicy?: RemovalPolicy;
  /**
   * A list of regions where to replicate this secret.
   *
   * @default - Secret is not replicated
   */
  readonly replicaRegions?: ReplicaRegion[];
  /**
   * Configure expiration notifications for secret keys.
   * When set, the Lambda syncer will detect keys ending with the expiration
   * suffix (e.g. `gitlab_token_expiration`) and create EventBridge Scheduler
   * one-time schedules to publish SNS notifications before each expiration.
   * Disabled by default.
   *
   * @default - Expiration notifications are disabled
   */
  readonly expiration?: ExpirationOptions;
}

/**
 * A drop in replacement for the normal Secret, that is populated with the encrypted
 * content of the given sops file.
 */
export class SopsSecret extends Construct implements ISecret {
  private readonly secret: Secret;
  readonly encryptionKey?: IKey | undefined;
  readonly secretArn: string;
  readonly secretFullArn?: string | undefined;
  readonly secretName: string;
  readonly secretRef: SecretReference;
  readonly stack: Stack;
  readonly env: ResourceEnvironment;

  /**
   * The SNS topic that receives expiration notifications.
   * Only set when `expiration` options are provided.
   */
  readonly expirationNotificationTopic?: ITopic;

  readonly sync: SopsSync;
  public constructor(scope: Construct, id: string, props: SopsSecretProps) {
    super(scope, id);
    this.secret = new Secret(this, 'Resource', props satisfies SecretProps);

    // Fullfill secret Interface
    this.encryptionKey = this.secret.encryptionKey;
    this.secretArn = this.secret.secretArn;
    this.secretName = this.secret.secretName;
    this.secretRef = this.secret.secretRef;
    this.stack = Stack.of(scope);
    this.env = {
      account: this.stack.account,
      region: this.stack.region,
    };

    let resourceType =
      props.sopsFileFormat == 'binary'
        ? ResourceType.SECRET_RAW
        : ResourceType.SECRET;
    if (props.rawOutput === RawOutput.BINARY) {
      resourceType = ResourceType.SECRET_BINARY;
    }
    if (props.rawOutput === RawOutput.STRING) {
      resourceType = ResourceType.SECRET_RAW;
    }

    let expirationConfig: SopsExpirationConfig | undefined;
    if (props.expiration !== undefined) {
      const topic =
        props.expiration.notificationTopic ??
        new Topic(this, 'ExpirationNotificationTopic');
      this.expirationNotificationTopic = topic;

      const schedulerRole = new Role(this, 'ExpirationSchedulerRole', {
        assumedBy: new ServicePrincipal('scheduler.amazonaws.com'),
        description:
          'Role assumed by EventBridge Scheduler to publish expiration notifications',
      });
      topic.grantPublish(schedulerRole);

      // Generate a deterministic, AWS-safe schedule group name from the construct path.
      // Schedule group names allow [a-zA-Z0-9_-], max 64 characters.
      const scheduleGroupName = Names.uniqueId(this)
        .replace(/[^a-zA-Z0-9_-]/g, '-')
        .substring(0, 64);

      new CfnScheduleGroup(this, 'ExpirationScheduleGroup', {
        name: scheduleGroupName,
      });

      expirationConfig = {
        topicArn: topic.topicArn,
        schedulerRoleArn: schedulerRole.roleArn,
        scheduleGroupName,
        expirationSuffix: props.expiration.expirationSuffix,
        daysBeforeExpiration: props.expiration.daysBeforeExpiration,
      };
    }

    this.sync = new SopsSync(this, 'SopsSync', {
      ...(props as SopsSyncOptions),
      target: this.secret.secretArn,
      resourceType,
      flattenSeparator: '.',
      secret: this.secret,
      expiration: expirationConfig,
    });
  }

  public currentVersionId(): string {
    return this.sync.versionId;
  }

  public grantRead(grantee: IGrantable, versionStages?: string[]): Grant {
    if (this.encryptionKey) {
      // @see https://docs.aws.amazon.com/kms/latest/developerguide/services-secrets-manager.html
      this.encryptionKey.grantDecrypt(
        new ViaServicePrincipal(
          `secretsmanager.${Stack.of(this).region}.amazonaws.com`,
          grantee.grantPrincipal,
        ),
      );
    }
    return this.secret.grantRead(grantee, versionStages);
  }
  public grantWrite(_grantee: IGrantable): Grant {
    throw new Error(
      `Method grantWrite(...) not allowed as this secret is managed by SopsSync`,
    );
  }
  public addRotationSchedule(
    id: string,
    options: RotationScheduleOptions,
  ): RotationSchedule {
    throw new Error(
      `Method addRotationSchedule('${id}', ${JSON.stringify(
        options,
      )}) not allowed as this secret is managed by SopsSync`,
    );
  }
  public addToResourcePolicy(
    statement: PolicyStatement,
  ): AddToResourcePolicyResult {
    return this.secret.addToResourcePolicy(statement);
  }
  public denyAccountRootDelete(): void {
    return this.secret.denyAccountRootDelete();
  }
  public attach(target: ISecretAttachmentTarget): ISecret {
    return this.secret.attach(target);
  }
  public cfnDynamicReferenceKey(options?: SecretsManagerSecretOptions): string {
    return this.secret.cfnDynamicReferenceKey(options);
  }
  public applyRemovalPolicy(policy: RemovalPolicy): void {
    return this.secret.applyRemovalPolicy(policy);
  }

  public secretValueFromJson(jsonField: string) {
    return SecretValue.secretsManager(this.secretArn, {
      jsonField,
      versionId: this.sync.versionId,
    });
  }

  public get secretValue(): SecretValue {
    return this.secretValueFromJson('');
  }
}
