name: build

on:
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CI: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install mise
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3
        with:
          experimental: true

      - name: Build (includes lambda test, lambda build, compile, test, integ verify)
        run: mise run build
