name: Scorecard supply-chain security

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * 1'

permissions: {}

jobs:
  analysis:
    runs-on: ubuntu-latest
    if: github.repository == 'dbsystel/cdk-sops-secrets'
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: ossf/scorecard-action@99c09fe975337306107572b4fdf4db224cf8e2f2 # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: scorecard-results
          path: results.sarif
          retention-days: 5

      - uses: github/codeql-action/upload-sarif@78ed0c7291d93e40c51b085850dc669a4c3ab73b # v3
        with:
          sarif_file: results.sarif
