name: validate-renovate-config

on:
  pull_request:
    paths:
      - "renovate.json"
  push:
    branches:
      - main
    paths:
      - "renovate.json"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Install mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4
        with:
          experimental: true

      - name: Validate Renovate config
        run: mise run renovate:validate
