name: validate-renovate-config

on:
  pull_request:
    paths:
      - "renovate.json"
  push:
    branches:
      - main
    paths:
      - "renovate.json"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false

      - name: Install mise
        uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4
        with:
          experimental: true

      - name: Validate Renovate config
        run: mise run renovate:validate
